apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: my-config
        - secretRef:
            name: backend-secret
